#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: AR - Lesson 01
#+date: <2021-10-11 lun>
#+author: Alessandro Straziota
#+email: alessandrostr95@gmail.com
#+teacher: Miriam Di Ianni
#+language: it
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.4.6)
#+setupfile: ../../org-template/appunti.org

* Analisi di Reti - definizione
  Nel senso più ampio del termine, una *rete* è uno schema di /interconnessioni/ tra entità.
  A seconda del tipo di entità e di interconnessioni, possono esistere diverse tipologie di reti, come:
  - reti di calcolatori che interagiscono tra di loro per eseguire task di computazione distribuita
  - le reti sociali, come per esmpio una rete di conoscenza di un social network
  - le reti di informazioni, ovvero il /web/
  - ...
  Lo studio di una rete po' interessare ed essere affrontato da differenti discipline: nella matematica/informatica
  studiando i modelli che le rappresentano e gli algoritmi che le coinvolgono, nelll'economia studiando le dinamiche
  di incentivo/disincentivo che influenzano il comportamento delle entità, o anche nelle scienze sociali per quanto riguarda i fenomi che influenzano
  i singoli individui o l'intera popolazione.
  Sostanzialmente, il modo in cui ci interesserà osservare una rete è come un ampio insieme di individui che reagisce in base al
  comportamento dei singoli.
  Quindi ci interesserà osservare come il comportamento locale di una entità influenza i fenomi globali dell'intera rete.\\
  
  L'analisi di una rete, nel nostro ambito d'interesse, verrà fatta considerando numerosi aspetti, come per esempio
  le *prestazioni*, la *struttura* e il loro *utilizzo*,e verranno anche analizzate le *tecniche* impiegate nell'analisi stessa.
  Alcuni aspetti strutturali che sono interessanti di analizzare sono:

** Fenomeno di diffusione
   In questo esempio verrà mostrato come i legami influiscono sul comportamento dei singoli individui.
   Supponiamo di giocare a una variante probabilistica del gioco del telefono in cui siamo disposti tutti in cerchio, e un volta
   ricevuto il messaggio lo passo solo se lanciando una moneta esce testa.
   La moneta è la stessa per tutti, però è *non* equa, ovvero esce testa con probabilità $p = 0.6$ e corce con probabilità $1-p = 0.4$.
   Se il cerchio è molto grande, è davvero molto poco probabile che il messaggio arrivi a un numero elevato di persone.
   Se invece per ogni persona nel cerchio associassimo un terzo "vicino" totlmente a caso a cui poter trasmettere il messaggio, succederà
   che /molto probabilmente/ il messaggio arriverà a una grossa porzione di persone in poco tempo.\\

   Questo esempio può essere paraganato al fenome della diffusione di un'infezione, in cui la probabilità di infettare un vicino non infetto (o
   che non è stato infettato in precedenza) è $p$ (vedi [[https://arxiv.org/abs/2103.16398][qui]]).

** Fenomeno di stabilità
   Un classico esempio in cui invece la presenza di legami influsce sulla struttura della rete è il seguente:
   consideriamo di avere una rete sociale in cui /Bob/ è amico di /Alice/ e di /Carol/, ma /Alice/ e /Carol/
   non si sopportano (perchè entrambe segretamente innamorate di /Bob/).
   Questa rete è detta *instabile*, in quanto per /Bob/ sarà difficle uscire con entrambe.
   Dovendo scegliere per forza una delle due con la quale passare più tempo, necessariamente il legame con l'altra
   tenderà a rompersi, rendendo così la rete più stabile.
   (Proprio non vorrei essere nei panni di /Bob/...).


* Struttura di una Rete
#+LABEL: sec:struttura
  Generalmente si è interessati a studiare reti di deminsioni enormi, perciò diventa estremamente complicato studiare ed analizzare
  ciò che accade ad ogni singolo individuo.
  Infatti ciò che si studia sono delle *proprietà globali* della rete.
  Esempi di proprietà globali interesanti sono

  1. esistenza di *componenti giganti*, ovvero se in un rete esiste una [[https://en.wikipedia.org/wiki/Strongly_connected_component][componente fortemente connessa]] molto grande (ovvero paragonabile alla grandezza della rete stessa).
   Un esperimento famoso a riguardo fu quello del 2006 condotto da /Leskovec & Horvitz/ in cui presero i dati (in maniera anonima?) delle
   comunicazioni fatte in un mese da 240 milioni di utenti di Instant Messenger.
   Su questi dati costruirono un grafo in cui i nodi erano i 240M di utenti, e inseririono un arco tra due nodi se i rispettivi utenti si
   scambiarono almeno un messaggio in quel mese.
   Risultò fuori l'esistenza di una componente fortemente connessa di circa 200 milioni di utenti.
  2. presenza di componenti (o porzioni di esse) *densamente connesse* (ovverro con un elevato numero di connessioni)
  3. verificare se la struttura della rete è di tipo *centro/periferica*
  4. verificare se la rete ha un *diametro* piccolo nonostante sia poco denso.

  Riguardo quest'ultimo punto è di dovere citare il famoso esperimento dello psicologo Stanley Milgram sui /"6 gradi di separazion"/.
  In pratica supponiamo di avere una lettera di volerla recapitare al presidente degli stati uniti.
  Sappiamo esattamente a chi farla arrivare, ma non come.
  Supponiamo di dare la lettera in mano al nostro conoscente che secondo noi è più probabile che la faccia arrivare al presidente, e
  diciamogli di fare lo stesso.
  Mediamente, tramite solo 5 intermediari, lattera arriverà al presidente Joe Biden.\\

  Lo studio di queste prorietà globali sarà fatto sia a /livello di popolazione/, ovvero considerando mediamente ciò che succede agli
  individui, sia a /livello di singolo individui/, andando a considerare la topologia della rete (relazione per relazione).


* Rappresentazione di una rete
  Come si è poptuto facilmente intuire in precedenza, il modo in cui verrà raffigurata una rete sarà tramite il modello
  matematico di /Grafo/.
  Si assume che i concetti e le definizioni base della teoria dei grafi siano ben note al lettore (se così non fosse,
  questi appunti non fanno per te... e nemmeno questo corso!).\\

  Supponiamo quendi di riuscire ad avere le informazioni di una rete reale (cosa che all'atto pratico non accade molto spesso),
  si potrebbe modellizzare semplicemente associando un nodo ad ogni entità della rete, e un arco per ogni interconnessione (facile no?).
  Fatto ciò si può "tranquillamente" procedere con l'analisi, alla ricerca di tutte le proprietà viste nella precedente [[sec:struttura][sezione]].\\

  Però, ammettendo pure di avere a disposizione questi dati, è difficle essere interessati a studiare le proprietà di una singola
  rete.
  Generlamente si è interessati a sapere proprietà *generali*, come per esempio qual è il diametro medio di una rete espresso in funzione
  del numero delle sue entità, oppure dato il grado medio dei nodi quanto sono grandi (mediamente) le componenti connesse.\\
  Per fare ciò bisognerebbe osservare un gran numero di reti!
  E in un contesto reale non si hanno così tante informazioni; un po' perché generalmente chi è in possesso di questi dati così
  preziosi difficilmente li condivide col mondo, un po' perchè di reti reali non ne esistono abbastanza da poter consentire di
  fare un'analisi statistica.\\
  Perciò quello che si fa generalmente è /inventare/ nuovi modelli di grafi che rispecchino il più possibile le proprietà che una
  rete reale possiede.
  Ovviemente non è possibile creare un medo che abbia *tutte* le proprietà di una rete reale, per via del grado di complissità delle ultime.
  Però in base al fenome che si desidera studiare, esistono dei modelli che presentano alcune proprietà abbastanza utili ai fini analitici.\\
  Perciò, una volta creato un modello, si possono *campionare* (o *istanziare*) quanti grafi si necessita.

** Il modello Erdős–Rényi
   Uno dei modelli più semplici e classici della letteratura è il cosiddetto /modello Erdős–Rényi/, noto anche come /Erdős–Rényi random graph/.
   Tale modello è definito come segue:\\

   siano $n \in \mathbb{N}$ e $p \in \left[ 0, 1 \right]$, $G_{n,p}$ è un grafo tale che:
   - $V = \left[ n \right] \equiv \{1,  2, ..., n \}$
   - $E \subseteq \binom{ V }{ 2 } : \forall u,v \in V \; \left[ \mathcal{P}( \{u, v\} \in E) = p \right]$

   Come si può notare tale modello è un /modello aleatorio/, da cui il nome /random graph/.
   Se ci si sofferma, l'insieme di archi $E$ segue una [[https://it.wikipedia.org/wiki/Distribuzione_binomiale][distribuzione binomiale]], perciò è corretto parlare anche
   di /distribuzione Erdős–Rényi/.\\

*** Componenti Giganti
    Una definizione più precisa di /componente gigante/ equivale a una /componente connessa/ grande una *frazione costante* dei nodi del grafo.
    Per frazione costante, si intende che al variare del numero di nodi del grafo, il rapporto tra $n$ e la grandezza della componente gigante
    rimane invariato.
    Si dice quindi che una componente gigante ha grandezza $\Theta(n)$, dove (ribadendo) $n$ è il numero di nodi del grafo.\\

    Per quanto riguarda la distribuzione /distribuzione Erdős–Rényi/ ci si potrebbe chiedere se esiste un valore di $p$ per cui
    esiste (con buona probabilità) una componente gigante in $G_{n,p}$, e se sì, per quale valore.\\

    Un risultato già noto dice che se $p > \frac{ \ln{64} }{ n }$ allora con /alta probabilità/ (/w.h.p./) esisterà una componente connessa
    con *almeno* la metà dei nodi.\\
    Il termine "alta probabilità" non è usato in maniera impropria, bensì cela un significato rigoroso e preciso.
    Per alta probabilità si intende con probabilità dell'ordine di _*almeno*_ $\left( 1 - \frac{ b }{ n^c } \right)$, per qualche coppia di costanti
    $b,c$ strettamente positive.\\

    Da cui quindi il seugente teorema:
    
    #+begin_quote
    *THM* sia $G_{n,p}$ un Erdős–Rényi random graph di parametri $n,p$, e sia $X$ la /variabile aleatori/ che indica il numero
    di nodi della più grande componente connessa di $G_{n,p}$.
    \[
    p > \frac{ \ln{64} }{ n } \implies \mathcal{P} \left( X \geq \frac{n}{2} \right) \geq 1 - 2^{-n/8}
    \]
    #+end_quote
    Per dimostrare il teorema è prima necessario introdurre il seguente lemma
    #+begin_quote
    *Lemma* Se $X < \frac{n}{2}$ allora esiste un insieme $A \subset \left[ n \right]$, detto /*insieme buono*/, tale che
    \[ \frac{n}{4} \leq |A| <    \frac{3}{4}n \]
    e
    \[ \nexists \{ u,v \} \in E : u \in A \land v \in [n] \setminus A \]
    #+end_quote

    #+begin_quote
    *Proof (Lemma)* Siano $C_1, C_2, ..., C_k$ tutte le componenti connesse di $G_{n,p}$ ordinate in
    senso non decrescente di grandezza, ovvero
    \[ |C_1| \leq |C_2| \leq ... \leq |C_k| := X < \frac{n}{2} \]
    Si scelga un indice $h$ tale che
    \[ |C_1| + |C_2| + ... |C_{h-1}| < \frac{n}{4} \]
    e
    \[ |C_1| + |C_2| + ... |C_{h-1}| + |C_h| \geq \frac{n}{4} \]
    Si osservi che necessariamente $h < k$, infatti poiché $|C_k| < \frac{n}{2}$,
    se fosse $h=k$ risulterebbe
    \[ |C_1| + |C_2| + ... |C_{k-1} | + |C_k | < \frac{n}{4} + \frac{n}{2} < n \]
    e questo è assurdo in quanto $C_1, C_2, ..., C_k$ sono una /partizione/ di $V$, perciò
    la dimensione della loro unione è esattamente $n$.\\

    Scelto un $h$ adeguato, poniamo $A = \bigcup_{i=1}^{h} C_h$.
    Necessariamente $A \neq \emptyset$ in quanto è composto da almeno $C_1$ (il quale ha almeno un nodo per definizione di componente),
    e $\left[ n \right] \setminus A \neq \emptyset$ in quanto al più $h$ può valere $k-1$ (lasciando fuori $C_k$ dall'insieme $A$).\\

    Seguono quindi le condizioni del lemma
    - $|A| \geq \frac{n}{4}$ per costruzione
    - $|A| = \underbrace{|C_1| + |C_2| + ... + |C_{k-1}|}_{ < n/4 } + \underbrace{|C_k|}_{< n/2} < \frac{n}{4} + \frac{n}{2} = \frac{3}{4}n$
    - Non ci possono essere archi nel taglio $(A,\left[ n \right] \setminus A)$, in quanto i due insiemi sono composti da componenti connesse.
      Infatti se esistesse un arco nel taglio, i due estremi apperterrebbero a due componenti connesse $C_i, C_j$ distinte,
      ma ciò significherebbe che $C_i \cup C_j$ è a sua volta una componente connessa (*assurdo!*).  $\square$
    #+end_quote

    Una diretta conseguenza del lemma è che la probabilità che la più grande componente connessa di $G_{n,p}$ sia più piccola di $n/2$ è
    *minore o uguale* alla probabilità sia presente un /insieme buono/.
    In fatti, in probabilità, dati due eventi $\mathcal{E_1},\mathcal{E_2}$, se $\mathcal{E_1} \implies \mathcal{E_2}$ allora
    $\mathcal{P}(\mathcal{E_1}) \leq \mathcal{P}(\mathcal{E_2})$.
    In questo caso gli eventi corrispondono $\mathcal{E_1}$ = "$X < n/2$" e $\mathcal{E_2}$ = "esiste un insieme buono $A$".\\

    #+begin_quote
    *Proof (THM)* Si deisdera calcolare $\mathcal{P}\left( X < \frac{n}{2} \right)$, ovvero il complementare della probabilità che si
    desidera dimostrare.\\

    Dal *Lemma* avremo che
    \[
    \mathcal{P}\left( X < \frac{n}{2} \right) \leq \mathcal{P}( \exists A \subset \left[ n \right] : A \mbox{ è buono})\\
    = \mathcal{P}\left( \bigcup_{A \subset \left[ n \right] \land \frac{n}{4} \leq |A| < \frac{3}{4}n }  A : \mbox{ non ci sono archi nel taglio } (A, \overline{A}) \right) \;\;\; \mbox{-- per definizione di insieme buono}\\
    \leq \sum_{A \subset \left[ n \right] \land \frac{n}{4} \leq |A| < \frac{3}{4}n } \mathcal{P}\left(\mbox{ non ci sono archi nel taglio } (A, \overline{A}) \right) \;\;\; \mbox{-- per il principio di union bound}\\
    = \sum_{A \subset \left[ n \right] \land \frac{n}{4} \leq |A| < \frac{3}{4}n } (1-p)^{|A| \cdot |\overline{A}|} \;\;\; \mbox{(1)}\\
    \leq \sum_{A \subset \left[ n \right] \land \frac{n}{4} \leq |A| < \frac{3}{4}n } (1-p)^{\frac{3}{16}n^2} \;\;\; \mbox{(2)}\\
    \leq 2^{n} (1-p)^{\frac{3}{16}n^2} \;\;\; (3)\\
    < 2^{n} \left(1 - \frac{ \ln{64} }{n} \right)^{\frac{3}{16}n^2} \;\;\; (4)\\
    = 2^{n} \left[ \left(1- \frac{ \ln{64} }{n} \right)^n \right]^{\frac{3}{16}n}\\
    = 2^{n} \left[ \left(1- \frac{ \ln{64} }{n} \right)^{n \cdot \left( \frac{ -\ln{64} }{ -\ln{64} }  \right)  } \right]^{\frac{3}{16}n}\\
    \approx 2^{n} \left[ e^{-\ln{64}}  \right]^{\frac{3}{16}n} \;\;\; (5)\\
    = 2^{n} \left[ 64^{-1}  \right]^{\frac{3}{16}n}\\
    = 2^{n} \left[ 2^{-6}  \right]^{\frac{3}{16}n} = 2^{n} 2^{ -\frac{18}{16}n } = 2^{-\frac{n}{8}} \;\;\; \square
    \]
   
    Di seguito spiegate le disuguaglianze:
    - *(1)* è data dal fatto che tale probabilità è data dalla probabilità che *non* esista un arco nel taglio, ovvero $(1-p)$, moltiplicato tante volte quanti i archi possono esistere tra $A$ e $\overline{A}$, ovvero $|A| \cdot |\overline{A}|$.
    - *(2)* è invece data dal fatto chef il punto di /minimo/ della funzione $|A| \cdot |\overline{A}|$ è per valori di $|A| = \frac{1}{4}, \frac{3}{4}$. Ci interessano i punti di minimo in quanto essendo $(1-p) < 1$, $(1-p)^{x}$ assume valori massimi per $x$ minimo.
    - *(3)* è dato dal fatto che il numero /massimo/ di sottoinsiemi $A \subseteq \left[ n \right]$ è $2^n$.
    - *(4)* per ipotesi del teorema
    - *(5)* perché $\lim_{n \rightarrow \infty} \left( 1 + \frac{1}{n} \right) = e^{n}$
    #+end_quote
    
    Una versione più generale del precedente teorema è la seguente
    #+begin_quote
    *Teorema generale* Sia $G_{n,p}$ un grafo aleatorio campionato dalla /distribuzione Erdős–Rényi/, allora:
    1. se $p(n-1) < 1$ allora /quasi sicuramente/ (/asymptotically almost surely/, o in breve /a.a.s./) tutte le componenti connesse di $G_{n,p}$ avranno $O( \log{n} )$ nodi (ovvero saranno molto piccole).
    2. se $p(n-1) = 1$ allora /a.a.s./ $G_{n,p}$ avrà una componente connessa grande $\approx n^{ \frac{2}{3} }$.
    3. se $p(n-1) > 1$ allora /a.a.s./ $G_{n,p}$ avrà una componente connessa grande $\Omega (n)$ nodi e tutte le altre grandi $O(\log{n})$.
    #+end_quote
    Ciò che suggerisce il teorema più generale è che la presenza di componenti connesse dipende 
    in qualche modo dal prodotto $p(n-1)$, ma cosa rappresenta questa quantità?
    Questo verrà mostrato nella seguente sezione.


*** Grado dei nodi
    Dato un grafo /Erdős–Rényi/ $G_{n,p}$, definiamo col simbolo $\delta_i$ la /variabile aleatoria/ che esprime il *grado* del nodo $i$.
    Sia inoltre  la v.a. binaria $j \in \left[ n \right] \setminus \lbrace i \rbrace$
    \[
    X_{i,j} = \begin{cases}
    1 &\mbox{se esiste l'arco }(i,j) \in E\\
    0 &\mbox{altrimenti}
    \end{cases}
    \]
    Perciò il [[https://it.wikipedia.org/wiki/Valore_atteso][valore atteso]] di $\delta_i$ sarà
    \[
    \mathbb{E} \left[ \delta_i  \right] = \mathbb{E} \left[ \sum_{j \in \left[ n \right] \setminus \lbrace i \rbrace } X_{i,j} \right]\\
    = \sum_{j \in \left[ n \right] \setminus \lbrace i \rbrace }  \mathbb{E} \left[  X_{i,j} \right] \;\;\; \mbox{(per linearità del valore atteso)}\\
    = \sum_{j \in \left[ n \right] \setminus \lbrace i \rbrace } 1 \cdot p + 0 \cdot (1-p) = (n-1)p
    \]
    Perciò la quantità $p(n-1)$ vista nella precedente sezione, altro non è che il /grado medio/ di un nodo.
    Ciò significa che, fissato un $p$ *costante*, ogni individuo nella rete sarà in contatto con una porzione constante della reta stessa, ovvero il grado medio cresce in maniera /lineare nel numero di nodi/.
    Ovviamente è inverosimile che in una rete di un social network composta da centinaia di milioni (se non miliardi) di nodi, io abbia un numero di amicizie proporzionale al numero di utenti (non penso sarà mai così famoso).\\

    Perciò, per modellare una rete che sia più verosimile, si potrebbe volere che $p$ sia una funzione di $n$, e che magari /descresca/ in maniera
    inversamente proporzionale, del tipo
    \[ p = p(n) = \frac{ \lambda }{n} \]
    Scegliendo $p$ in questa maniera, avremo che il grado medio di un nodo sarà pari alla *costante* $\lambda$, indipendentemente dalla dimensione della rete.\\

    Un'altra domanda che è utile chiedersi è: fissato un $k \leq n$, con quale probabilità che un nodo $i \in \left[ n \right]$ ha *esattamente* grado $k$.
    Intuitivamente, questa è pari alla probabilità che esistano esattamente $k$ archi incidenti a $i$.
    Tale probabilità è esattamente definita dalla [[https://it.wikipedia.org/wiki/Distribuzione_binomiale][legge binomiale]] $\mathcal{B}(n-1,p)$, ovvero
    \[
    \mathcal{P}\left( \delta_i = k \right) = \binom{n-1}{k} p^k \left( 1-p \right)^{(n-1) - k}
    \]
    Questo perché:
    1. $\binom{n-1}{k}$ è il numero di tutte le possibili $k$-uple di nodi in $\left[ n \right] \setminus \lbrace i \rbrace $.
    2. $p^k$ è la probabilità che eistano gli archi tra $i$ e i nodi di una $k$-upla.
    3. $\left( 1-p \right)^{(n-1) - k}$ è la probabilità che non esista nessun altro arco (ne vogliamo solo $k$).
    
    Scegliendo $p = \frac{ \lambda }{n}$ in funzione di $n$ come detto in precedenza, avremo che la probabilità che un nodo abbia grado
    medio esattamente $k$ è
    \[
    \mathcal{P}\left( \delta_i = k \right) = \binom{n-1}{k} p^k \left( 1-p \right)^{(n-1) - k}\\
    \binom{n-1}{k} \left(  \frac{ \lambda }{n} \right)^k \left( 1-  \frac{ \lambda }{n} \right)^{(n-1) - k}\\
    = \frac{(n-1) \cdot (n-2) \cdot ... \cdot (n-k)}{k!} \frac{ \lambda^k }{ n^k } \left( 1-  \frac{ \lambda }{n} \right)^{(n-1) - k}\\
    < \frac{(n-1) \cdot (n-2) \cdot ... \cdot (n-k)}{k!} \frac{ \lambda^k }{ n^k } e^{ \frac{-\lambda (n - 1 - k)}{n}} \;\;\; (1)\\
    < \frac{n^k}{k!} \frac{ \lambda^k }{ n^k } e^{ \frac{-\lambda (n - 1 - k)}{n}}\\
    \approx \frac{ \lambda^k }{ k! } e^{ -\lambda } \;\;\; \mbox{per } n \mbox{ sufficientemente grande}
    \]
    Più semplicemente
    \[ \mathcal{P}\left( \delta_i = k \right) < \frac{ \lambda^k }{ k! } e^{ -\lambda } \]

    Applicando l'[[https://it.wikipedia.org/wiki/Approssimazione_di_Stirling][approssimazione di Stirling]] secondo la quale $k! \thicksim \sqrt{2 \pi k} \left( \frac{k}{e}  \right)^k$,
    
