#+title: AR - Lesson 14
#+date: <2021-12-06>
#+teacher: Miriam Di Ianni
#+setupfile: ../../org-template/appunti.org
#+options: num:nil

* Sistemi di Voto Posizionali
  Supponiamo che i voti individuali siano espressi sotto forma di _ranking_ \((r_1, ..., r_k) \in \Pi(\left[ n \right])^k\).
  Una classe diversa di sistemi di voto cerca di produrre un ranking di gruppo $r$ _direttamente_ dalle classifiche individuali \(r_1, ..., r_k\),
  piuttosto che costruire $r$ da confronti tra coppie di alternative.\\

  In un sistema di voto *posizionale* a ciascun ranking \(r_h\) viene assegnata una *funzione peso* \(w_h\) la quale associa un valore numerico a ciascuna alternativa
  _dipendentemente_ dalla sua posizione nel ranking \(r_h\).
  Tale funzione \(w_h\) per essere sensata è tipicamente decrescente, ovvero se un'alternativa $a$ sta in una posizione bassa (tra i primi posti) rispetto a \(r_h\) avrà un peso \(w_h(a)\) alto,
  viceversa se $a$ sta verso gli ultimi posti allora \(w_h(a)\) assumerà un valore più basso.\\

  Un esempio di funzione peso \(w_h\) per il ranking \(r_h = \langle a_{h1}, ..., a_{hn} \rangle\) è la seguente
  \[
  w_h(a_{hi}) = \frac{1}{i} \;\; \forall i \in \left[ n \right]
  \]

  Una volta associata una funzione peso ad ogni ranking si calcola il *peso collettivo* di un'alternativa $a$ semplicemente sommando i pesi dei seingoli rankingk, ovvero
  \[
  w(a) = \sum_{h = 1}^{k} w_h(a)
  \]
  Infine le alternative vengono quindi ordinate in base al loro peso totale, e in base ad esse definito un ranking collettibo $r$.

  Il *Borda Count* è un particolare sistema di /voto posizionale/ nel quale per ogni votante \(h \in \left[ k \right]\) la funzione di peso associata al ranking \(r_h\) è definita come segue
  \[
  \rho_h(a_{hi}) = n - i \;\;\; \forall i \in \left[ n \right]
  \]

** Problema dell ex aequo
   Anche nei sistemi posizionali si manigesta il /paradosso di Condorcet/ sotto forma di *ex aequo* (pareggio).

   Consideriamo ancora una volta l'esempio dei tre amici che devono andare in campeggio, visto nella [[./13.html][lezione precedente]].
   Le tre classifiche erano
   - =A=: \(\langle\)🍫, 🍒, 🍯\(\rangle\).
   - =B=: \(\langle\)🍒, 🍯, 🍫\(\rangle\).
   - =C=: \(\langle\)🍯, 🍫, 🍒\(\rangle\).

   Applichiamo ora il Borda Count, ottendo le seguenti funzioni peso
   \begin{array}{ccc}
     \rho_A(🍫) = 2 & \rho_A(🍒) = 1 & \rho_A(🍯) = 0\\
     \rho_B(🍒) = 2 & \rho_B(🍯) = 1 & \rho_B(🍫) = 0\\
     \rho_C(🍯) = 2 & \rho_C(🍫) = 1 & \rho_C(🍒) = 0
   \end{array}

   Alla fine otteremo un pareggio tra i pesi finali
   \[
   \rho(🍫) = \rho(🍒) = \rho(🍯) = 3
   \]
   Perciò è necessario supporre che se due alternative ricevono lo stesso peso totale, allora viene utilizzato un sistema di *spareggio* organizzato in anticipo per decidere quale di queste due alternative posizionare di fronte all'altra.

** Rilevanza delle Alternative Irrilevanti
   Consideriamo una rassegna cinematografica, in cui una giuria composta da cinque critici =A=, =B=, =C=, =D=, =E= deve eleggere un vincitore tra i film /"Via col Vento"/ (alternativa =VV=) e /"Il Padrino"/ (alternativa =IP=).
   Tre guidici su 5 ritengono che =VV= sia il film che debba vincere.
   Le classifiche riultano quindi essere

   #+attr_html: :align center
   #+caption: Classifiche dei 5 giudici.
   | Giudici | 1° posto        | 2° posto        |
   |---------+-----------------+-----------------|
   | =A=     | /Via col Vento/ | /Il Padrino/    |
   | =B=     | /Il Padrino/    | /Via col Vento/ |
   | =C=     | /Via col Vento/ | /Il Padrino/    |
   | =D=     | /Il Padrino/    | /Via col Vento/ |
   | =E=     | /Via col Vento/ | /Il Padrino/    |
   |---------+-----------------+-----------------|

   A questo punto gli organizzatori nella rassegna decidono di introdurre un novo film nella gara, /"Pulp Fiction"/ (alternativa =PF=).\\

   Tutta la giuria è d'accordo che =PF= non è all'altezza della competizione e che quindi non può vincere.
   Tuttavia i player =B= e =D= (i due che preferiscono =IP= a =VV=) possono creare un ranking in modo tale da far vincere il loro preferito.
   Infatti ponendo =PF= al secondo posto nella loro classifica, e =VV= all'utlimo, possono compromettere il risultato finale.

   #+attr_html: :align center
   #+caption: Nuove classifiche.
   | Giudici | 1° posto        | 2° posto       | 3° posto        |
   |---------+-----------------+----------------+-----------------|
   | =A=     | /Via col Vento/ | /Il Padrino/   | /Pulp Fiction/  |
   | =B=     | /Il Padrino/    | /Pulp Fiction/ | /Via col Vento/ |
   | =C=     | /Via col Vento/ | /Il Padrino/   | /Pulp Fiction/  |
   | =D=     | /Il Padrino/    | /Pulp Fiction/ | /Via col Vento/ |
   | =E=     | /Via col Vento/ | /Il Padrino/   | /Pulp Fiction/  |
   |---------+-----------------+----------------+-----------------|

   Con questa nuova graduatoria avremo i seguenti pesi collettivi
   \begin{align*}
     \rho(\texttt{``Via col Vento''}) &= 6\\
     \rho(\texttt{``Il Padrino''}) &= 7\\
     \rho(\texttt{``Pulp Fiction''}) &= 2
   \end{align*}

   In pratica, classificando in maniera opportuna l'*alternativa irrilevante* (ovvero =PF=) si riesce a compromettere la graduatoria finale della competizione.
   Questo è uno dei problemi principali di cui soffrono i sistemi di voto posizionali.

* Sistemi di Voto Affidabili
  Fin ora abbiamo incontrato alcune tipologie di sistemi di voto, ognuna affetta da "patologie" (problematiche che lo rendono non del tutto affidabile).
  Alcune problematiche incontrate sono state
  - *Paradosso di Condorcet*: col sistema a maggioranza non risco sempre ad individuare una classifica finale coerente.
  - *Strategic Agenda Setting*: col sistema a torneo la graduatoria finale dipende dall'ordinamento iniziale delle alterantive.
  - *Alternative Irrilevanti*: nel sistema posizionale si possono classificare le alternative irrilevanti per condizionare la graduatoria finale.

  Ad questo punto ha senso fare un passo indietro dai sistemi di voto specifici e porsi una domanda più generale:
  #+begin_quote
  /esiste un sistema di voto che produca una classifica collettiva (per tre o più alternative) evitando tutte le "patologie" precedentemente descritte?/
  #+end_quote
  o meglio ancora
  #+begin_quote
  /riusciamo a definire un sistema di voto sempre *affidabile*?/
  #+end_quote

  Per quanto visto in precedenza, un paio di condizioni _minime_ per avere l'affidabilità di un sistema di voto sono:
  - il voto finale deve rappresentare le scelte di tutti i votanti qualora tutti siano d'accordo su qualcosa.
  - non deve essere possibile sfruttare le alternative irrilevanti per modificare la graduatoria finale.

  Per quanto riguarda il paradosso di Condorcet, se esprimiamo la graduatoria finale in termini di ranking $r$ avremo sempre una classifica non ambigua (basta introdurre un metodo imparziale per lo spareggio).\\

  Analiziamo ora in maniera più formale le due condizioni minime per ottenere un sistema di voto affidamile.

** Principio di Paretro - Unanimità
   Sia \(\sigma\) un /sistema di voto/ con $n$ alternative e $k$ votanti.
   Siano i ranking \((r_1, ..., r_k) \in \Pi(\left[ n \right])^k\) dei $k$ partecipanti.
   Indichiamo con $r$ il _voto collettivo_ ruspetto ai ranking \(r_1, ..., r_k\), tali che
   \[
   \sigma(r_1, ..., r_k, r) = \texttt{True}
   \]
   In fine, per ogni votante \(h \in \left[ k \right]\) indichiamo la funzione di peso Borda count \(\rho_h\) rispetto a \(r_h\),
   e la funzione \(\rho\) rispetto al voto collettivo $r$.\\

   Il principio dell'*Unanimità* (o *Principio di Paretro*) vuole che nel caso in cui un'alternativa =X= è preferita ad un'alternativa =Y= per _tutti_ i votanti \(h \in \left[ k \right]\),
   allora anche nella graduatoria finale =X= deve essere preferito a =Y=.
   Più formalmente
   \[
   \forall i,j \in \left[ n \right]\\
   \left[
   \forall h \in \left[ k \right] \rho_h(i) > \rho_h(j)
   \implies \rho(i) > \rho(j)
   \right]
   \]

   D'ora in poi ci riferiremo al principio dell'unanimità con =U=.

** Principio d'Indipendenza dalle Alternative Irrilevanti
   Sia \(\sigma\) un /sistema di voto/ con $n$ alternative e $k$ votanti.\\
   
   Il principio dell'*Indipendenza dalle Alternative Irrilevanti* si richiede che per ogni coppia di alternative =X=, =Y= il loro ordinamento nella graduatoria finale $r$ dipende
   _unicamente_ dalle posizioni relative rispetto alle graduatorie individuali.
   In poche parole, se in una graduatoria finale =X= è preferita ad =Y=, anche se introduciamo una nuova alternativa =Z=, il sistema deve produrre un nuovo ranking in cui =X= rimane ancora il preferito rispetto a =Y=.\\

   Più formalmente
   \[
   \forall i,j \in \left[ n \right]
   \forall (r_1, ..., r_k), (r'_1, ..., r'_k) \in \Pi(\left[ n \right])^k\\
   \left[
   \left( \forall h \in \left[ k \right] \rho_h(i) > \rho_h(j) \iff \rho'_h(i) > \rho'_h(j) \right)\\
   \implies \left( \rho(i) > \rho(j) \iff \rho'(i) > \rho'(j) \right)
   \right]
   \]
   dove \(\rho'\) è il Borda count collettivo rispetto al ranking \((r'_1, ..., r'_k)\), in accordo col sistema di voto \(\sigma\).\\

   D'ora in poi ci riferiremo al principio dell'indipendenza dalle alternative irrilevanti con =IIA=.

* Il Teorema (di Impossibilità) di Arrow
  *[DA FINIRE...]*

   
